  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
            with:
              token: ${{ secrets.PAGES_TOKEN }}
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Install packages
            run: npm i
          - name: Set Creds
            run: git config user.name "ivanlay" && git config user.email "13257861+ivanlay@users.noreply.github.com"
          - name: Deploy
            run: npm run deploy